controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint1
        - joint2
        - joint3
      state_publish_rate: 25
      action_monitor_rate: 10
      constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.01
      gains:
        joint1:
          p: 100.0
          d: 10.0
          i: 1.0
          i_clamp: 1.0
        joint2:
          p: 100.0
          d: 10.0
          i: 1.0
          i_clamp: 1.0
        joint3:
          p: 100.0
          d: 10.0
          i: 1.0
          i_clamp: 1.0
